name: Deploy

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Deploy the Voila Gallery
      uses: appleboy/ssh-action@v0.0.4
      with:
        host: ${{ secrets.VOILA_GALLERY_HOST }}
        username: ${{ secrets.VOILA_GALLERY_SSH_USERNAME }}
        key: ${{ secrets.VOILA_GALLERY_SSH_PRIVATE_KEY }}
        script: |
          sudo /opt/tljh/hub/bin/python3 -m pip install -U  git+https://github.com/voila-dashboards/gallery@master#"egg=tljh-voila-gallery&subdirectory=tljh-voila-gallery"
          sudo systemctl restart jupyterhub.service
          sudo systemctl status jupyterhub.service

    - name: Check voila-gallery.org is reachable
      run: |
        sleep 30
        curl -sSf https://voila-gallery.org > /dev/null
